services:
  api:
    build: .
    container_name: eneverre-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: mediamtx
    restart: always
    ports:
      - 8554:8554
      - 8888:8888
      - 9996:9996
    volumes:
     - ./data/mediamtx.yml:/mediamtx.yml
